name: Validate changes

on:
  push:
    branches: [preview]
  pull_request:
    branches: [preview, main]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run check:content
      - run: npm run lint
      - name: Build Preview
        if: github.event_name == 'push' || github.base_ref == 'preview'
        run: npm run build:preview
      - name: Build Production
        if: (github.event_name == 'push' && github.ref == 'refs/heads/preview') || (github.event_name == 'pull_request' && github.base_ref == 'main')
        run: npm run build
